### ISSUE TITLE
Update jib to 3.3+

### ISSUE THREAD

**Issue by tomcham** [sbt-jib/sbt-jib#89]
Hello,

Any plans to update jib to 3.3+? The newer distroless java images (ex. [this one](https://console.cloud.google.com/gcr/images/distroless/GLOBAL/java17-debian11@sha256:6e135f309fb112dcf820fc64b4465772bc045d7bf9fb75fd4cf7e6cf8eed5e47/details?tag=latest)) are using [OCI Image Index Specification](https://github.com/opencontainers/image-spec/blob/main/image-index.md#oci-image-index-specification). Jib added support in [3.3.0](https://github.com/GoogleContainerTools/jib/blob/master/jib-maven-plugin/CHANGELOG.md#330).

Error msg I'm getting when running `jibImageBuild`

```
[error] com.google.cloud.tools.jib.registry.RegistryErrorException: Tried to pull image manifest for gcr.io/distroless/java17-debian11:latest but failed because: Manifest with tag 'latest' has media type 'application/vnd.oci.image.index.v1+json', but client accepts 'application/vnd.oci.image.manifest.v1+json,application/vnd.docker.distribution.manifest.v2+json,application/vnd.docker.distribution.manifest.v1+json,application/vnd.docker.distribution.manifest.list.v2+json'. | If this is a bug, please file an issue at https://github.com/GoogleContainerTools/jib/issues/new
[error] 	at com.google.cloud.tools.jib.registry.RegistryErrorExceptionBuilder.build(RegistryErrorExceptionBuilder.java:105)
[error] 	at com.google.cloud.tools.jib.registry.RegistryEndpointCaller.newRegistryErrorException(RegistryEndpointCaller.java:213)
[error] 	at com.google.cloud.tools.jib.registry.RegistryEndpointCaller.call(RegistryEndpointCaller.java:154)
[error] 	at com.google.cloud.tools.jib.registry.RegistryEndpointCaller.call(RegistryEndpointCaller.java:115)
[error] 	at com.google.cloud.tools.jib.registry.RegistryClient.callRegistryEndpoint(RegistryClient.java:624)
[error] 	at com.google.cloud.tools.jib.registry.RegistryClient.pullManifest(RegistryClient.java:436)
[error] 	at com.google.cloud.tools.jib.registry.RegistryClient.pullManifest(RegistryClient.java:441)
[error] 	at com.google.cloud.tools.jib.builder.steps.PullBaseImageStep.pullBaseImages(PullBaseImageStep.java:290)
[error] 	at com.google.cloud.tools.jib.builder.steps.PullBaseImageStep.call(PullBaseImageStep.java:157)
[error] 	at com.google.cloud.tools.jib.builder.steps.PullBaseImageStep.call(PullBaseImageStep.java:69)
```

**Comment by sideeffffect** [comment]
We're using the latest jib-core
https://github.com/GoogleContainerTools/jib/blob/master/jib-core/CHANGELOG.md#0230
https://github.com/sbt-jib/sbt-jib/blob/master/build.sbt#L29

I'm not sure what to do here :(

**Comment by tomcham** [comment]
You're right, I misunderstood. The issue i'm facing seems to be unrelated.

**Comment by sideeffffect** [comment]
And btw the current jib-core should allow `OciIndexTemplate.MEDIA_TYPE`
https://github.com/GoogleContainerTools/jib/blob/master/jib-core/src/main/java/com/google/cloud/tools/jib/registry/AbstractManifestPuller.java#L92
